# Generated by Django 5.1.15 on 2026-04-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressionLecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecon_lue', models.BooleanField(default=False, verbose_name='leçon lue')),
                ('date_debut_lecture', models.DateTimeField(blank=True, null=True, verbose_name='début de lecture')),
                ('date_fin_lecture', models.DateTimeField(blank=True, null=True, verbose_name='fin de lecture')),
                ('temps_passe_secondes', models.PositiveIntegerField(default=0, verbose_name='temps passé (s)')),
            ],
            options={
                'verbose_name': 'progression leçon',
                'verbose_name_plural': 'progressions leçons',
            },
        ),
        migrations.CreateModel(
            name='QuestionLibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='question')),
                ('reponse', models.TextField(blank=True, verbose_name='réponse')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('jetons_entree', models.PositiveIntegerField(default=0, verbose_name="jetons d'entrée")),
                ('jetons_sortie', models.PositiveIntegerField(default=0, verbose_name='jetons de sortie')),
            ],
            options={
                'verbose_name': 'question libre',
                'verbose_name_plural': 'questions libres',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ReponseDonnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correcte', models.BooleanField(default=False, verbose_name='correcte')),
                ('date_reponse', models.DateTimeField(auto_now_add=True, verbose_name='date de réponse')),
            ],
            options={
                'verbose_name': 'réponse donnée',
                'verbose_name_plural': 'réponses données',
                'ordering': ['date_reponse'],
            },
        ),
        migrations.CreateModel(
            name='TentativeQCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True, verbose_name='début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='fin')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='score')),
                ('total_questions', models.PositiveSmallIntegerField(default=0, verbose_name='total questions')),
                ('terminee', models.BooleanField(default=False, verbose_name='terminée')),
            ],
            options={
                'verbose_name': 'tentative de QCM',
                'verbose_name_plural': 'tentatives de QCM',
                'ordering': ['-date_debut'],
            },
        ),
    ]
