# Generated by Django 5.1.15 on 2026-04-21 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenu', '0002_initial'),
        ('progression', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='progressionlecon',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions_lecon', to=settings.AUTH_USER_MODEL, verbose_name='élève'),
        ),
        migrations.AddField(
            model_name='progressionlecon',
            name='thematique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='contenu.thematique', verbose_name='thématique'),
        ),
        migrations.AddField(
            model_name='questionlibre',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_libres', to=settings.AUTH_USER_MODEL, verbose_name='élève'),
        ),
        migrations.AddField(
            model_name='questionlibre',
            name='thematique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_libres', to='contenu.thematique', verbose_name='thématique (contexte)'),
        ),
        migrations.AddField(
            model_name='reponsedonnee',
            name='proposition_choisie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reponses_donnees', to='contenu.proposition', verbose_name='proposition choisie'),
        ),
        migrations.AddField(
            model_name='reponsedonnee',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_donnees', to='contenu.questionqcm', verbose_name='question'),
        ),
        migrations.AddField(
            model_name='tentativeqcm',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives_qcm', to=settings.AUTH_USER_MODEL, verbose_name='élève'),
        ),
        migrations.AddField(
            model_name='tentativeqcm',
            name='thematique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives', to='contenu.thematique', verbose_name='thématique'),
        ),
        migrations.AddField(
            model_name='reponsedonnee',
            name='tentative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='progression.tentativeqcm', verbose_name='tentative'),
        ),
        migrations.AddConstraint(
            model_name='progressionlecon',
            constraint=models.UniqueConstraint(fields=('eleve', 'thematique'), name='progression_unique_par_eleve_thematique'),
        ),
        migrations.AddConstraint(
            model_name='reponsedonnee',
            constraint=models.UniqueConstraint(fields=('tentative', 'question'), name='reponse_unique_par_tentative_question'),
        ),
    ]
