# Generated by Django 5.1.15 on 2026-04-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsommationAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('type_appel', models.CharField(choices=[('generation_lecon', 'Génération de leçon'), ('generation_qcm', 'Génération de QCM'), ('question_libre', 'Question libre'), ('autre', 'Autre')], max_length=20, verbose_name="type d'appel")),
                ('modele', models.CharField(max_length=80, verbose_name='modèle')),
                ('jetons_entree', models.PositiveIntegerField(default=0, verbose_name="jetons d'entrée")),
                ('jetons_sortie', models.PositiveIntegerField(default=0, verbose_name='jetons de sortie')),
                ('cout_estime_euros', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='coût estimé (€)')),
            ],
            options={
                'verbose_name': 'consommation API',
                'verbose_name_plural': 'consommations API',
                'ordering': ['-date'],
            },
        ),
    ]
