# Generated by Django 5.1.15 on 2026-04-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChapitreProgramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('objectifs', models.TextField(blank=True, help_text='Compétences du Bulletin officiel visées par ce chapitre.', verbose_name='objectifs')),
                ('ordre_programme', models.PositiveSmallIntegerField(default=0, verbose_name='ordre dans le programme')),
            ],
            options={
                'verbose_name': 'chapitre du programme',
                'verbose_name_plural': 'chapitres du programme',
                'ordering': ['matiere__ordre', 'ordre_programme'],
            },
        ),
        migrations.CreateModel(
            name='Lecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='contenu Markdown')),
                ('mots_cles', models.JSONField(blank=True, default=list, verbose_name='mots-clés')),
                ('duree_lecture_estimee', models.PositiveSmallIntegerField(default=10, verbose_name='durée de lecture estimée (minutes)')),
                ('modele_ia_utilise', models.CharField(blank=True, max_length=80, verbose_name='modèle IA utilisé')),
                ('version_prompt', models.CharField(blank=True, help_text='Version du prompt de génération (voir docs/prompts_ia.md).', max_length=20, verbose_name='version du prompt')),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='date de génération')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
            options={
                'verbose_name': 'leçon',
                'verbose_name_plural': 'leçons',
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='code')),
                ('nom', models.CharField(max_length=80, verbose_name='nom')),
                ('couleur', models.CharField(default='#4f46e5', help_text="Code hexadécimal utilisé pour l'affichage (ex. #4f46e5).", max_length=7, verbose_name='couleur')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'matière',
                'verbose_name_plural': 'matières',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(verbose_name='texte')),
                ('est_correcte', models.BooleanField(default=False, verbose_name='est correcte')),
                ('explication', models.TextField(blank=True, verbose_name='explication')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'proposition',
                'verbose_name_plural': 'propositions',
                'ordering': ['question', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='QuestionQCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enonce', models.TextField(verbose_name='énoncé')),
                ('difficulte', models.PositiveSmallIntegerField(default=2, verbose_name='difficulté')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('explication_generale', models.TextField(blank=True, verbose_name='explication générale')),
            ],
            options={
                'verbose_name': 'question de QCM',
                'verbose_name_plural': 'questions de QCM',
                'ordering': ['thematique', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Thematique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_jour', models.PositiveSmallIntegerField(blank=True, help_text="Position dans le plan annuel global (1 à 180). Attribué après import via une commande d'ordonnancement.", null=True, unique=True, verbose_name='numéro de jour global')),
                ('numero_dans_matiere', models.PositiveSmallIntegerField(help_text='Position dans le plan annuel de la matière (numérotation locale du fichier plan_annuel_*.md).', verbose_name='numéro dans la matière')),
                ('titre', models.CharField(max_length=200, verbose_name='titre')),
                ('objectifs_apprentissage', models.TextField(blank=True, verbose_name="objectifs d'apprentissage")),
                ('notions', models.TextField(blank=True, verbose_name='notions abordées')),
                ('prerequis', models.TextField(blank=True, verbose_name='pré-requis')),
                ('mots_cles', models.JSONField(blank=True, default=list, verbose_name='mots-clés')),
                ('difficulte', models.PositiveSmallIntegerField(default=2, verbose_name='difficulté')),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('generee', 'Générée'), ('validee', 'Validée'), ('archivee', 'Archivée')], default='planifiee', max_length=12, verbose_name='statut')),
                ('date_prevue', models.DateField(blank=True, null=True, verbose_name='date prévue')),
            ],
            options={
                'verbose_name': 'thématique',
                'verbose_name_plural': 'thématiques',
                'ordering': ['matiere__ordre', 'numero_dans_matiere'],
            },
        ),
    ]
