# Generated by Django 5.1.15 on 2026-04-21 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lecon',
            name='validee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecons_validees', to=settings.AUTH_USER_MODEL, verbose_name='validée par'),
        ),
        migrations.AddField(
            model_name='chapitreprogramme',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to='contenu.matiere', verbose_name='matière'),
        ),
        migrations.AddField(
            model_name='proposition',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions', to='contenu.questionqcm', verbose_name='question'),
        ),
        migrations.AddField(
            model_name='thematique',
            name='chapitre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thematiques', to='contenu.chapitreprogramme', verbose_name='chapitre'),
        ),
        migrations.AddField(
            model_name='thematique',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thematiques', to='contenu.matiere', verbose_name='matière'),
        ),
        migrations.AddField(
            model_name='questionqcm',
            name='thematique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='contenu.thematique', verbose_name='thématique'),
        ),
        migrations.AddField(
            model_name='lecon',
            name='thematique',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lecon', to='contenu.thematique', verbose_name='thématique'),
        ),
        migrations.AddConstraint(
            model_name='chapitreprogramme',
            constraint=models.UniqueConstraint(fields=('matiere', 'titre'), name='chapitre_unique_par_matiere'),
        ),
        migrations.AddConstraint(
            model_name='proposition',
            constraint=models.UniqueConstraint(fields=('question', 'ordre'), name='proposition_ordre_unique_par_question'),
        ),
        migrations.AddConstraint(
            model_name='thematique',
            constraint=models.UniqueConstraint(fields=('matiere', 'numero_dans_matiere'), name='thematique_unique_par_matiere'),
        ),
        migrations.AddConstraint(
            model_name='questionqcm',
            constraint=models.UniqueConstraint(fields=('thematique', 'ordre'), name='question_ordre_unique_par_thematique'),
        ),
    ]
